<a href="https://colab.research.google.com/github/mowreee/googol-colab/blob/main/Delos_Santos_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
#1. Create a NumPy Array of Zeros
import numpy as np
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [27]:
#2. Create a 2D Array with Specific Values
arr = np.full((2, 3), 7)
print(arr)

[[7 7 7]
 [7 7 7]]


In [28]:
#3. Create an Array of Even Numbers from 10 to 50
arr = np.arange(10, 51, 2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [29]:
#4. Create an Identity Matrix
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
#5. Reshape a 1D Array to 2D
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
matrix_3x3 = arr_1d.reshape(3, 3)
print(matrix_3x3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
#6. Array Slicing
arr = np.arange(1, 11)
extracted_values = arr[arr > 5]
print(extracted_values)

[ 6  7  8  9 10]


In [32]:
#7. Perform Element-wise Addition
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b
print(result)

[5 7 9]


In [33]:
#8. Find Maximum and Minimum in an Array
arr = np.array([3, 9, 0, -1, 5])
max_value = np.max(arr)
min_value = np.min(arr)
print(f"Max: {max_value}")
print(f"Min: {min_value}")

Max: 9
Min: -1


In [34]:
#9. Genarate Random Numbers
random_matrix = np.random.rand(3, 3)
print(random_matrix)

[[0.0548421  0.71848985 0.74670555]
 [0.37084918 0.20293584 0.2222574 ]
 [0.32921632 0.72444841 0.74815868]]


In [35]:
#10. Multiply a Matrix by a Scalar
import numpy as np
arr = np.array([[1, 2], [3, 4]])
scalar_value = 3
result = arr * scalar_value
print(result)

[[ 3  6]
 [ 9 12]]


In [36]:
#11. Matrix Multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = np.dot(a, b)
print(result)

[[19 22]
 [43 50]]


In [37]:
#12. Transpose a Matrix
arr = np.array([[1, 2], [3, 4]])
transposed_arr = np.transpose(arr)
print(transposed_arr)

[[1 3]
 [2 4]]


In [38]:
#13. Compute Mean, Median, and Standard Deviation
arr = np.array([10, 20, 30, 40, 50])
mean_value = np.mean(arr)
median_value = np.median(arr)
std_dev_value = np.std(arr)
print(f"Mean: {mean_value}")
print(f"Median: {median_value}")
print(f"Std Dev: {std_dev_value:.2f}")

Mean: 30.0
Median: 30.0
Std Dev: 14.14


In [39]:
#14. Boolean Indexing
arr = np.array([5, 10, 15, 20])
elements_greater_than_10 = arr[arr > 10]
print(elements_greater_than_10)

[15 20]


In [40]:
#15. Flatten a Multi-dimensional Array
arr_2d = np.array([[1, 2], [3, 4]])
arr_1d = arr_2d.flatten()
print(arr_1d)

[1 2 3 4]
